version: '3'

services:
  fastapi_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    volumes:
      - ./data_text:/data_text
    env_file:
      - .env