version: '3'

services:
  server:
    build:
      context: server/
      dockerfile: Dockerfile_server
    ports:
      - "10000:10000"
    networks:
      - app
    env_file:
      - server/.env
  client:
    build:
      context: client/
      dockerfile: Dockerfile_client
    ports:
      - "8501:8501"
    networks:
      - app
    env_file:
      - client/.env

networks:
  app:
    driver: bridge